version: "3.9"

services:
  starrfox_bot:
    working_dir: /discord_chan
    command: poetry run discord_chan
    build:
      context: .
      dockerfile: ./Dockerfile
    secrets:
      - discord_token
    environment:
      IN_DOCKER: "true"

secrets:
  discord_token:
    file: ./discord_token.secret