[tool.poetry]
name = "discord_chan"
version = "2.4.6"
description = "General purpose Discord bot"
authors = ["StarrFox <starrfox6312@gmail.com>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.25.2"
uwuify = "^1.3.0"
click = "^8.1.7"
loguru = "^0.7.0"
humanize = "^4.8.0"
psutil = "^5.9.5"
uvloop = {version = "^0.17.0", markers = "platform_system == 'Linux'"}
Unidecode = "^1.3.6"
"discord.py" = "^2.3.2"
jishaku = "^2.5.1"
discord-ext-menus = {git = "https://github.com/Rapptz/discord-ext-menus"}
pendulum = "^2.1.2"
asyncpg = "^0.28.0"
parsedatetime = "^2.6"

[tool.poetry.scripts]
discord-chan = "discord_chan.__main__:main"

[tool.poetry.group.images.dependencies]
wand = "^0.6.11"
pillow = "^10.0.0"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_type = "semver"
version_provider = "poetry"
update_changelog_on_bump = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
