[tool.poetry]
name = "discord_chan"
version = "2.19.2"
description = "General purpose Discord bot"
authors = ["StarrFox <starrfox6312@gmail.com>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^1.26.4"
uwuify = "^1.3.1"
click = "^8.1.7"
loguru = "^0.7.0"
humanize = "^4.9.0"
psutil = "^5.9.8"
uvloop = {version = "^0.19.0", markers = "platform_system == 'Linux'"}
Unidecode = "^1.3.8"
"discord.py" = "^2.3.2"
jishaku = "^2.5.2"
discord-ext-menus = {git = "https://github.com/Rapptz/discord-ext-menus"}
pendulum = "^3.0.0"
asyncpg = "^0.29.0"
parsedatetime = "^2.6"
typing-extensions = "^4.11.0"
loguru-logging-intercept = "^0.1.4"

[tool.poetry.scripts]
discord_chan = "discord_chan.__main__:main"

[tool.poetry.group.images.dependencies]
wand = "^0.6.11"
pillow = "^10.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
